-- ============================================================
-- Data Analysis & Business Key Problems & Answers
-- ============================================================


-- My Analysis & Findings
-- Q.1 Find the total revenue generated in the dataset.
-- Q.2 Find the average Sales_Amount for all transactions.
-- Q.3 Display the top 5 highest sales transactions.
-- Q.4 Count the total number of transactions made by each Sales_Rep
-- Q.5 Find the total quantity sold for each Product_Category.
-- Q.6 Count how many customers are New and how many are Returning.
-- Q.7 Find the total revenue generated by each Sales_Rep and display them in descending order.
-- Q.8 Show the top 3 regions with the highest total sales.
-- Q.9 Find the monthly sales trend using Sale_Date.
-- Q.10 Find the salesperson who sold the highest total quantity of products
-- Q.11 Find the average discount given for each Product_Category.
-- Q.12 Show transactions where the discount is greater than 20%.
-- Q.13 Find which Product_Category generated the highest revenue.
-- Q.14 Compare total sales between Online and Retail sales channels.
-- Q.15 Find which customer type (New or Returning) contributes more revenue.


-- A.) Sales & Revenue

-- 1.) Total revenue generated in the dataset.

SELECT Round(SUM(Sales_Amount),2) AS Total_Revenue 
FROM sales_data;

-- Insights:
-- The dataset generated significant total revenue,
-- showing strong overall business performance.


-- 2.) Average Sales_Amount for all transactions.

SELECT Round(AVG(Sales_Amount),2) AS Avg_Sales_Amount
FROM sales_data;

-- 3.)Top 5 highest sales transactions.

SELECT * 
FROM sales_data 
ORDER BY Sales_Amount DESC 
LIMIT 5;

-- Insights:
-- Top transactions contribute significantly to total revenue,
-- highlighting the importance of high-value customers.


-- 4.)Total number of transactions made by each Sales_Rep

SELECT Sales_Rep,count(*) AS Total_Transaction
FROM sales_data 
GROUP BY Sales_Rep
ORDER BY Total_Transaction DESC;

-- Insight:
-- Some sales representatives handle significantly more transactions than others,
-- indicating performance differences within the sales team.


-- B.) Product Category

-- 5.)Total quantity sold for each Product_Category.

SELECT Product_Category,SUM(Quantity_Sold) AS Total_Quantity_Sold
FROM sales_data
GROUP BY Product_Category 
ORDER BY Total_Quantity_Sold DESC;

-- Insight:
-- Clothing product category dominate total quantity sold,
-- reflecting higher customer demand in Clothing.


-- C.) Customer & Payment

-- 6.) Count how many customers are New and how many are Returning.

SELECT Customer_Type,COUNT(*) AS Total_Customers 
FROM sales_data
GROUP BY Customer_Type
ORDER BY Total_Customers DESC;


-- D.) Sales Performance

-- 7.)Total revenue generated by each Sales_Rep and display them in descending order.

SELECT Sales_Rep,ROUND(SUM(Sales_Amount),2) AS Total_Revenue
FROM sales_data
GROUP BY Sales_Rep
ORDER BY Total_Revenue DESC;

-- Insight:
-- Top-performing sales representatives contribute a major share of revenue,
-- highlighting strong individual sales performance.

-- 8.) Top 3 regions with the highest total sales.

SELECT Region,ROUND(SUM(Sales_Amount),2) AS Total_Sales
FROM sales_data
GROUP BY Region
ORDER BY  Total_sales DESC 
LIMIT 3;

-- Insight:
-- North regions contribute heavily to overall revenue,
-- indicating strong market demand in north areas.


-- 9.) Monthly sales trend using Sale_Date.

SELECT MONTH(STR_TO_DATE(Sale_Date,'%d-%m-%Y')) AS Month_Number,ROUND(SUM(Sales_Amount),2) AS Monthly_Sales
FROM sales_data
GROUP BY Month_Number
ORDER BY Month_Number;

-- Insight:
-- Some months like Jan,Oct,Nov recorded higher sales,
-- possibly due to seasonal demand patterns.



-- 10.) Salesperson who sold the highest total quantity of products.

SELECT Sales_Rep, SUM(Quantity_Sold) AS Total_Quantity
FROM sales_data
GROUP BY Sales_Rep 
ORDER BY Total_Quantity DESC limit 1;


-- E.) Product & Discount Analysis

-- 11.) Average discount given for each Product_Category.

SELECT Product_Category,ROUND(AVG(Discount),2) AS Avg_Discount
FROM sales_data
GROUP BY Product_Category
ORDER BY Avg_Discount DESC;

-- Insight:
-- Furniture and Clothing categories receive higher average discounts,
-- which may impact profitability.


-- 12.) Transactions where the discount is greater than 20%.

SELECT * 
FROM sales_data
WHERE (Discount*100)>20;

-- Observation:
-- High-discount transactions may have been used to boost sales volume.


-- 13.) Find which Product_Category generated the highest revenue.

SELECT Product_Category,ROUND(SUM(sales_Amount),2) AS Revenue
FROM sales_data
GROUP BY Product_Category
ORDER BY Revenue DESC LIMIT 1;

-- Insight:
-- Clothing is the highest revenue-generating category is a key driver of business profitability.



-- F.) Customer & Channel Insights

-- 14.) Compare total sales between Online and Retail sales channels.

SELECT Sales_Channel,SUM(Sales_Amount) AS Total_sales 
FROM sales_data
GROUP BY Sales_Channel
ORDER BY total_sales DESC;

-- Insight:
-- Retail sales outperform Online sales,
-- indicating growing customer preference for Retail purchasing.



-- 15.) Find which customer type (New or Returning) contributes more revenue.

SELECT Customer_Type,ROUND(SUM(Sales_Amount),2) AS Total_Revenue
FROM sales_data
GROUP BY Customer_Type
ORDER BY Total_Revenue DESC;


-- Insight:
-- Returning customers contribute more revenue than new customers,
-- emphasizing the importance of customer retention strategies.
